version: "3"

services:
  netology-db:
    image: postgres:latest # Для прод. указывать версию
    container_name: KalashnikovDA-netology-db
    ports:
      - 5432:5432
    volumes:
      - ./pg_data:/var/lib/postgresql/data/pgdata
    environment:
      POSTGRES_PASSWORD: KalashnikovDA12!3!! # Задаём пароль от пользователя postgres
      POSTGRES_DB: KalashnikovDA-netology_db # БД которая сразу же будет создана
      PGDATA: /var/lib/postgresql/data/pgdata # Путь внутри контейнера, где будет папка pgdata
    networks:
      Kalashnikov-DA-my-netology-hw:
        ipv4_address: 172.22.0.3
    restart: always

  pgadmin:
    image: dpage/pgadmin4
    container_name: KalashnikovDA-netology-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: KalashnikovDA@ilove-netology.com
      PGADMIN_DEFAULT_PASSWORD: 123
    ports:
      - "61231:80"
    networks:
      Kalashnikov-DA-my-netology-hw:
        ipv4_address: 172.22.0.4
    restart: always

  zabbix-server:
    image: zabbix/zabbix-server-pgsql
    links:
    - netology-db
    container_name: kalashnikovDA-netology-zabbix
    environment:
      DB_SERVER_HOST: '172.22.0.3'
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: KalashnikovDA12!3!!
    ports:
      - "10051:10051"
    networks:
      Kalashnikov-DA-my-netology-hw:
        ipv4_address: 172.22.0.5
    restart: always

  zabbix_wgui:
    image: zabbix/zabbix-web-apache-pgsql
    links:
    - netology-db
    container_name: KalashnikovDA-netology-zabbix-frontend
    environment:
      DB_SERVER_HOST: '172.22.0.3'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: KalashnikovDA12!3!!
      ZBX_SERVER_HOST: "zabbix_wgui"
      PHP_TZ: "Asia/Novosibirsk"
    ports:
      - "80:8080"
      - "443:8443"
    networks:
      Kalashnikov-DA-my-netology-hw:
        ipv4_address: 172.22.0.6
    restart: always

networks:
  Kalashnikov-DA-my-netology-hw:
    driver: bridge
    ipam:
      config:
      - subnet: 172.22.0.0/24
